version = "2.0.5"

[PATH]
config_file= "/etc/gpu_tool/config.toml" #配置文件
main_file = "/usr/local/bin/gpu_tool"  #主程序
fd_path = "/home/houmao/fd"  #fieldiag路径
gpu_burn_path = "/home/houmao/gpu-burn"  #gpu_burn路径
nccl_path = "/home/houmao/nccl-tests/build"  #nccl测试路径
fd_exe = "fieldiag.sh"  #fieldiag可执行文件
gpu_burn_exe = "gpu_burn"  #gpu_burn可执行文件
nccl_exe = "all_reduce_perf"  #nccl可执行文件


[UPDATE]
#待实现，不用管
url = "http://192.168.10.20"  #更新地址
update_file = "/gpu_tool"  #更新文件路径
update_config = "/update.json"  #更新配置文件

[LOG]
log_path = "/home/houmao/log"  #日志路径
log_file = "gpu_tool_debug.log"  #日志文件
log_level = "INFO"  #日志级别
console_output = false
